CREATE TABLE ipl_teams (
    team_id int PRIMARY KEY,
    team_name VARCHAR(100),
    city VARCHAR(100),
    owner VARCHAR(100),
    coach VARCHAR(100),
    captain VARCHAR(100),
    home_ground VARCHAR(100),
    founded_year INTEGER
);

INSERT INTO ipl_teams (team_id, team_name, city, owner, coach, captain, home_ground, founded_year) VALUES
(1, 'Mumbai Indians', 'Mumbai', 'Reliance Industries', 'Mark Boucher', 'Hardik Pandya', 'Wankhede Stadium', 2008),
(2, 'Chennai Super Kings', 'Chennai', 'India Cements', 'Stephen Fleming', 'Ruturaj Gaikwad', 'M. A. Chidambaram Stadium', 2008),
(3, 'Royal Challengers Bangalore', 'Bangalore', 'United Spirits Limited', 'Andy Flower', 'Faf du Plessis', 'M. Chinnaswamy Stadium', 2008),
(4, 'Kolkata Knight Riders', 'Kolkata', 'Knight Riders Group', 'Chandrakant Pandit', 'Shreyas Iyer', 'Eden Gardens', 2008),
(5, 'Delhi Capitals', 'New Delhi', 'JSW Group and GMR Group', 'Ricky Ponting', 'Rishabh Pant', 'Arun Jaitley Stadium', 2008),
(6, 'Rajasthan Royals', 'Jaipur', 'Manoj Badale', 'Kumar Sangakkara', 'Sanju Samson', 'Sawai Mansingh Stadium', 2008),
(7, 'Sunrisers Hyderabad', 'Hyderabad', 'Sun TV Network', 'Daniel Vettori', 'Pat Cummins', 'Rajiv Gandhi International Stadium', 2012),
(8, 'Punjab Kings', 'Mohali', 'Preity Zinta, Ness Wadia, Mohit Burman, Karan Paul', 'Trevor Bayliss', 'Shikhar Dhawan', 'Punjab Cricket Association IS Bindra Stadium', 2008),
(9, 'Gujarat Titans', 'Ahmedabad', 'CVC Capital Partners', 'Ashish Nehra', 'Shubman Gill', 'Narendra Modi Stadium', 2022),
(10, 'Lucknow Super Giants', 'Lucknow', 'RPSG Group', 'Justin Langer', 'KL Rahul', 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 2022),
(11, 'Deccan Chargers', 'Hyderabad', 'Gayatri Reddy', NULL, NULL, 'Rajiv Gandhi International Stadium', 2008),
(12, 'Kochi Tuskers Kerala', 'Kochi', 'Kochi Cricket Pvt Ltd', NULL, NULL, 'Jawaharlal Nehru Stadium', 2011),
(13, 'Pune Warriors India', 'Pune', 'Sahara India Pariwar', NULL, NULL, 'Maharashtra Cricket Association Stadium', 2011),
(14, 'Rising Pune Supergiant', 'Pune', 'Sanjiv Goenka', NULL, NULL, 'Maharashtra Cricket Association Stadium', 2016),
(15, 'Rising Pune Supergiants', 'Pune', 'Sanjiv Goenka', NULL, NULL, 'Maharashtra Cricket Association Stadium', 2017),
(16, 'Gujarat Lions', 'Rajkot', 'Keshav Bansal', NULL, NULL, 'Saurashtra Cricket Association Stadium', 2016),
(17, 'Kolkata Knight Riders', 'Kolkata', 'Red Chillies Entertainment, Mehta Group', 'John Buchanan', 'Sourav Ganguly', 'Eden Gardens', 2008),
(18, 'Chennai Super Kings', 'Chennai', 'India Cements', 'Geoff Marsh', 'MS Dhoni', 'M. A. Chidambaram Stadium', 2008),
(19, 'Rajasthan Royals', 'Jaipur', 'Emerging Media', 'Shane Warne', 'Shane Warne', 'Sawai Mansingh Stadium', 2008),
(20, 'Delhi Daredevils', 'Delhi', 'GMR Group', 'Greg Shipperd', 'Virender Sehwag', 'Feroz Shah Kotla Ground', 2008),
(21, 'Mumbai Indians', 'Mumbai', 'Reliance Industries', 'Lalchand Rajput', 'Sachin Tendulkar', 'Wankhede Stadium', 2008),
(22, 'Deccan Chargers', 'Hyderabad', 'Gayatri Reddy', 'Tom Moody', 'V. V. S. Laxman', 'Rajiv Gandhi International Stadium', 2008),
(23, 'Royal Challengers Bangalore', 'Bangalore', 'United Spirits Limited', 'Ray Jennings', 'Rahul Dravid', 'M. Chinnaswamy Stadium', 2008),
(24, 'Kings XI Punjab', 'Mohali', 'Preity Zinta, Ness Wadia', 'Tom Moody', 'Yuvraj Singh', 'Punjab Cricket Association Stadium', 2008),
(25, 'Kochi Tuskers Kerala', 'Kochi', 'Rendezvous Sports World', 'Geoff Lawson', 'Mahela Jayawardene', 'Jawaharlal Nehru Stadium', 2011),
(26, 'Pune Warriors India', 'Pune', 'Sahara India Pariwar', 'Geoff Marsh', 'Yuvraj Singh', 'Maharashtra Cricket Association Stadium', 2011),
(27, 'Sunrisers Hyderabad', 'Hyderabad', 'Sun TV Network', 'Tom Moody', 'Kumar Sangakkara', 'Rajiv Gandhi International Stadium', 2013),
(28, 'Rajasthan Royals', 'Jaipur', 'Manoj Badale', 'Paddy Upton', 'Rahul Dravid', 'Sawai Mansingh Stadium', 2013),
(29, 'Mumbai Indians', 'Mumbai', 'Reliance Industries', 'John Wright', 'Rohit Sharma', 'Wankhede Stadium', 2013),
(30, 'Chennai Super Kings', 'Chennai', 'India Cements', 'Stephen Fleming', 'MS Dhoni', 'M. A. Chidambaram Stadium', 2013),
(31, 'Royal Challengers Bangalore', 'Bangalore', 'United Spirits Limited', 'Daniel Vettori', 'Virat Kohli', 'M. Chinnaswamy Stadium', 2013),
(32, 'Kings XI Punjab', 'Mohali', 'Preity Zinta, Ness Wadia', 'Darren Lehmann', 'Adam Gilchrist', 'Punjab Cricket Association Stadium', 2013),
(33, 'Delhi Daredevils', 'Delhi', 'GMR Group', 'Eric Simons', 'Mahela Jayawardene', 'Feroz Shah Kotla Ground', 2013),
(34, 'Sunrisers Hyderabad', 'Hyderabad', 'Sun TV Network', 'Tom Moody', 'Shikhar Dhawan', 'Rajiv Gandhi International Stadium', 2014),
(35, 'Kings XI Punjab', 'Mohali', 'Preity Zinta, Ness Wadia', 'Sanjay Bangar', 'George Bailey', 'Punjab Cricket Association Stadium', 2014),
(36, 'Kolkata Knight Riders', 'Kolkata', 'Knight Riders Group', 'Trevor Bayliss', 'Gautam Gambhir', 'Eden Gardens', 2014),
(37, 'Chennai Super Kings', 'Chennai', 'India Cements', 'Stephen Fleming', 'MS Dhoni', 'M. A. Chidambaram Stadium', 2014),
(38, 'Rajasthan Royals', 'Jaipur', 'Manoj Badale', 'Paddy Upton', 'Shane Watson', 'Sawai Mansingh Stadium', 2014),
(39, 'Mumbai Indians', 'Mumbai', 'Reliance Industries', 'John Wright', 'Rohit Sharma', 'Wankhede Stadium', 2014),
(40, 'Royal Challengers Bangalore', 'Bangalore', 'United Spirits Limited', 'Daniel Vettori', 'Virat Kohli', 'M. Chinnaswamy Stadium', 2014),
(41, 'Gujarat Lions', 'Rajkot', 'Keshav Bansal', 'Brad Hodge', 'Suresh Raina', 'Saurashtra Cricket Association Stadium', 2016),
(42, 'Rising Pune Supergiants', 'Pune', 'Sanjiv Goenka', 'Stephen Fleming', 'MS Dhoni', 'Maharashtra Cricket Association Stadium', 2016),
(43, 'Sunrisers Hyderabad', 'Hyderabad', 'Sun TV Network', 'Tom Moody', 'David Warner', 'Rajiv Gandhi International Stadium', 2016),
(44, 'Kolkata Knight Riders', 'Kolkata', 'Knight Riders Group', 'Jacques Kallis', 'Gautam Gambhir', 'Eden Gardens', 2016),
(45, 'Mumbai Indians', 'Mumbai', 'Reliance Industries', 'Ricky Ponting', 'Rohit Sharma', 'Wankhede Stadium', 2016),
(46, 'Royal Challengers Bangalore', 'Bangalore', 'United Spirits Limited', 'Daniel Vettori', 'Virat Kohli', 'M. Chinnaswamy Stadium', 2016),
(47, 'Rising Pune Supergiant', 'Pune', 'Sanjiv Goenka', 'Stephen Fleming', 'Steve Smith', 'Maharashtra Cricket Association Stadium', 2017),
(48, 'Gujarat Lions', 'Rajkot', 'Keshav Bansal', 'Brad Hodge', 'Suresh Raina', 'Saurashtra Cricket Association Stadium', 2017),
(49, 'Kolkata Knight Riders', 'Kolkata', 'Knight Riders Group', 'Jacques Kallis', 'Gautam Gambhir', 'Eden Gardens', 2017),
(50, 'Mumbai Indians', 'Mumbai', 'Reliance Industries', 'Mahela Jayawardene', 'Rohit Sharma', 'Wankhede Stadium', 2017);

select * from ipl_teams 


CREATE TABLE ipl_matches (
    match_id INT ,
    season INTEGER NOT NULL,
    match_date DATE NOT NULL,
    team1_id INT,
    team2_id INT,
    venue VARCHAR(100),
    match_winner_id INT,
    result VARCHAR(200),
    FOREIGN KEY (team1_id) REFERENCES ipl_teams(team_id),
    FOREIGN KEY (team2_id) REFERENCES ipl_teams(team_id),
    FOREIGN KEY (match_winner_id) REFERENCES ipl_teams(team_id)
);


INSERT INTO ipl_matches (match_id, season, match_date, team1_id, team2_id, venue, match_winner_id, result) VALUES
(1, 2023, '2023-03-31', 1, 2, 'Wankhede Stadium', 1, 'Mumbai Indians won by 5 wickets'),
(2, 2023, '2023-04-01', 8, 4, 'Punjab Cricket Association IS Bindra Stadium', 8, 'Punjab Kings won by 7 runs'),
(3, 2023, '2023-04-02', 10, 5, 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 10, 'Lucknow Super Giants won by 50 runs'),
(4, 2023, '2023-04-02', 7, 6, 'Rajiv Gandhi International Stadium', 6, 'Rajasthan Royals won by 4 wickets'),
(5, 2023, '2023-04-03', 3, 1, 'M. Chinnaswamy Stadium', 3, 'Royal Challengers Bangalore won by 8 wickets'),
(6, 2023, '2023-04-04', 5, 9, 'Arun Jaitley Stadium', 9, 'Gujarat Titans won by 6 wickets'),
(7, 2023, '2023-04-05', 6, 8, 'Sawai Mansingh Stadium', 8, 'Punjab Kings won by 5 runs'),
(8, 2023, '2023-04-06', 2, 10, 'M. A. Chidambaram Stadium', 2, 'Chennai Super Kings won by 12 runs'),
(9, 2023, '2023-04-07', 9, 4, 'Narendra Modi Stadium', 9, 'Gujarat Titans won by 7 wickets'),
(10, 2023, '2023-04-08', 8, 10, 'Punjab Cricket Association IS Bindra Stadium', 8, 'Punjab Kings won by 2 wickets'),
(11, 2023, '2023-04-09', 1, 3, 'Wankhede Stadium', 1, 'Mumbai Indians won by 6 wickets'),
(12, 2023, '2023-04-10', 9, 6, 'Narendra Modi Stadium', 6, 'Rajasthan Royals won by 3 wickets'),
(13, 2023, '2023-04-11', 5, 1, 'Arun Jaitley Stadium', 1, 'Mumbai Indians won by 6 wickets'),
(14, 2023, '2023-04-12', 2, 6, 'M. A. Chidambaram Stadium', 2, 'Chennai Super Kings won by 8 runs'),
(15, 2023, '2023-04-13', 8, 9, 'Punjab Cricket Association IS Bindra Stadium', 9, 'Gujarat Titans won by 6 wickets'),
(16, 2023, '2023-04-14', 4, 7, 'Eden Gardens', 4, 'Kolkata Knight Riders won by 5 runs'),
(17, 2023, '2023-04-15', 3, 5, 'M. Chinnaswamy Stadium', 3, 'Royal Challengers Bangalore won by 23 runs'),
(18, 2023, '2023-04-16', 1, 4, 'Wankhede Stadium', 1, 'Mumbai Indians won by 5 wickets'),
(19, 2023, '2023-04-17', 10, 9, 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 10, 'Lucknow Super Giants won by 33 runs'),
(20, 2023, '2023-04-18', 6, 10, 'Sawai Mansingh Stadium', 6, 'Rajasthan Royals won by 10 runs'),
(21, 2022, '2022-03-26', 2, 4, 'Wankhede Stadium', 4, 'Kolkata Knight Riders won by 6 wickets'),
(22, 2022, '2022-03-27', 5, 1, 'Brabourne Stadium', 5, 'Delhi Capitals won by 4 wickets'),
(23, 2022, '2022-03-27', 8, 3, 'DY Patil Stadium', 8, 'Punjab Kings won by 5 wickets'),
(24, 2022, '2022-03-28', 9, 10, 'Wankhede Stadium', 9, 'Gujarat Titans won by 5 wickets'),
(25, 2022, '2022-03-29', 7, 6, 'Maharashtra Cricket Association Stadium', 6, 'Rajasthan Royals won by 61 runs'),
(26, 2022, '2022-03-30', 3, 4, 'DY Patil Stadium', 3, 'Royal Challengers Bangalore won by 3 wickets'),
(27, 2022, '2022-03-31', 10, 2, 'Brabourne Stadium', 10, 'Lucknow Super Giants won by 6 wickets'),
(28, 2022, '2022-04-01', 4, 8, 'Wankhede Stadium', 4, 'Kolkata Knight Riders won by 6 wickets'),
(29, 2022, '2022-04-02', 1, 6, 'DY Patil Stadium', 6, 'Rajasthan Royals won by 23 runs'),
(30, 2022, '2022-04-02', 9, 5, 'Maharashtra Cricket Association Stadium', 9, 'Gujarat Titans won by 14 runs'),
(31, 2021, '2021-04-09', 1, 3, 'MA Chidambaram Stadium', 3, 'Royal Challengers Bangalore won by 2 wickets'),
(32, 2021, '2021-04-10', 2, 5, 'Wankhede Stadium', 5, 'Delhi Capitals won by 7 wickets'),
(33, 2021, '2021-04-11', 7, 4, 'MA Chidambaram Stadium', 4, 'Kolkata Knight Riders won by 10 runs'),
(34, 2021, '2021-04-12', 6, 8, 'Wankhede Stadium', 6, 'Rajasthan Royals won by 4 runs'),
(35, 2021, '2021-04-13', 1, 5, 'MA Chidambaram Stadium', 1, 'Mumbai Indians won by 6 wickets'),
(36, 2021, '2021-04-14', 7, 3, 'MA Chidambaram Stadium', 3, 'Royal Challengers Bangalore won by 6 runs'),
(37, 2021, '2021-04-15', 6, 5, 'Wankhede Stadium', 6, 'Rajasthan Royals won by 3 wickets'),
(38, 2021, '2021-04-16', 8, 2, 'Wankhede Stadium', 2, 'Chennai Super Kings won by 6 wickets'),
(39, 2021, '2021-04-18', 3, 4, 'MA Chidambaram Stadium', 3, 'Royal Challengers Bangalore won by 38 runs'),
(40, 2021, '2021-04-18', 5, 8, 'Wankhede Stadium', 5, 'Delhi Capitals won by 6 wickets'),
(41, 2020, '2020-09-19', 1, 2, 'Sheikh Zayed Stadium', 2, 'Chennai Super Kings won by 5 wickets'),
(42, 2020, '2020-09-20', 5, 8, 'Dubai International Cricket Stadium', 5, 'Delhi Capitals won by Super Over'),
(43, 2020, '2020-09-21', 7, 3, 'Dubai International Cricket Stadium', 3, 'Royal Challengers Bangalore won by 10 runs'),
(44, 2020, '2020-09-22', 6, 2, 'Sharjah Cricket Stadium', 6, 'Rajasthan Royals won by 16 runs'),
(45, 2020, '2020-09-23', 4, 1, 'Sheikh Zayed Stadium', 1, 'Mumbai Indians won by 49 runs'),
(46, 2020, '2020-09-24', 3, 8, 'Dubai International Cricket Stadium', 8, 'Punjab Kings won by 97 runs'),
(47, 2020, '2020-09-25', 2, 5, 'Dubai International Cricket Stadium', 5, 'Delhi Capitals won by 44 runs'),
(48, 2020, '2020-09-26', 7, 4, 'Sheikh Zayed Stadium', 4, 'Kolkata Knight Riders won by 7 wickets'),
(49, 2020, '2020-09-27', 6, 8, 'Sharjah Cricket Stadium', 6, 'Rajasthan Royals won by 4 wickets'),
(50, 2020, '2020-09-28', 3, 1, 'Dubai International Cricket Stadium', 3, 'Royal Challengers Bangalore won by Super Over');

select * from ipl_matches


CREATE TABLE ipl_players (
    player_id SERIAL PRIMARY KEY,
    player_name VARCHAR(100) NOT NULL,
    team_id INTEGER NOT NULL,
    nationality VARCHAR(50),
    role VARCHAR(50),
    batting_style VARCHAR(50),
    bowling_style VARCHAR(50),
    FOREIGN KEY (team_id) REFERENCES ipl_teams(team_id)
);


INSERT INTO ipl_players (player_name, team_id, nationality, role, batting_style, bowling_style) VALUES
('Rohit Sharma', 1, 'Indian', 'Batsman', 'Right-handed bat', 'Right-arm off break'),
('Jasprit Bumrah', 1, 'Indian', 'Bowler', 'Right-handed bat', 'Right-arm fast'),
('Suryakumar Yadav', 1, 'Indian', 'Batsman', 'Right-handed bat', 'Right-arm medium'),
('Ishan Kishan', 1, 'Indian', 'Batsman', 'Left-handed bat', NULL),
('Cameron Green', 1, 'Australian', 'All-rounder', 'Right-handed bat', 'Right-arm medium-fast'),
('MS Dhoni', 2, 'Indian', 'Wicket-keeper Batsman', 'Right-handed bat', NULL),
('Ravindra Jadeja', 2, 'Indian', 'All-rounder', 'Left-handed bat', 'Left-arm orthodox'),
('Ruturaj Gaikwad', 2, 'Indian', 'Batsman', 'Right-handed bat', NULL),
('Moeen Ali', 2, 'English', 'All-rounder', 'Left-handed bat', 'Right-arm off break'),
('Deepak Chahar', 2, 'Indian', 'Bowler', 'Right-handed bat', 'Right-arm medium'),
('Virat Kohli', 3, 'Indian', 'Batsman', 'Right-handed bat', 'Right-arm medium'),
('Glenn Maxwell', 3, 'Australian', 'All-rounder', 'Right-handed bat', 'Right-arm off break'),
('Faf du Plessis', 3, 'South African', 'Batsman', 'Right-handed bat', NULL),
('Mohammed Siraj', 3, 'Indian', 'Bowler', 'Right-handed bat', 'Right-arm fast-medium'),
('Wanindu Hasaranga', 3, 'Sri Lankan', 'All-rounder', 'Right-handed bat', 'Right-arm leg break'),
('Shreyas Iyer', 4, 'Indian', 'Batsman', 'Right-handed bat', NULL),
('Andre Russell', 4, 'West Indian', 'All-rounder', 'Right-handed bat', 'Right-arm fast'),
('Sunil Narine', 4, 'West Indian', 'All-rounder', 'Left-handed bat', 'Right-arm off break'),
('Varun Chakaravarthy', 4, 'Indian', 'Bowler', 'Right-handed bat', 'Right-arm leg break'),
('Nitish Rana', 4, 'Indian', 'Batsman', 'Left-handed bat', 'Right-arm off break'),
('Rishabh Pant', 5, 'Indian', 'Wicket-keeper Batsman', 'Left-handed bat', NULL),
('David Warner', 5, 'Australian', 'Batsman', 'Left-handed bat', NULL),
('Axar Patel', 5, 'Indian', 'All-rounder', 'Left-handed bat', 'Left-arm orthodox'),
('Anrich Nortje', 5, 'South African', 'Bowler', 'Right-handed bat', 'Right-arm fast'),
('Kuldeep Yadav', 5, 'Indian', 'Bowler', 'Left-handed bat', 'Left-arm chinaman'),
('Sanju Samson', 6, 'Indian', 'Wicket-keeper Batsman', 'Right-handed bat', NULL),
('Jos Buttler', 6, 'English', 'Batsman', 'Right-handed bat', NULL),
('Yuzvendra Chahal', 6, 'Indian', 'Bowler', 'Right-handed bat', 'Right-arm leg break'),
('Trent Boult', 6, 'New Zealander', 'Bowler', 'Left-handed bat', 'Left-arm fast-medium'),
('Riyan Parag', 6, 'Indian', 'All-rounder', 'Right-handed bat', 'Right-arm leg break'),
('Aiden Markram', 7, 'South African', 'Batsman', 'Right-handed bat', 'Right-arm off break'),
('Bhuvneshwar Kumar', 7, 'Indian', 'Bowler', 'Right-handed bat', 'Right-arm medium'),
('T. Natarajan', 7, 'Indian', 'Bowler', 'Left-handed bat', 'Left-arm medium-fast'),
('Heinrich Klaasen', 7, 'South African', 'Wicket-keeper Batsman', 'Right-handed bat', NULL),
('Washington Sundar', 7, 'Indian', 'All-rounder', 'Left-handed bat', 'Right-arm off break'),
('Shikhar Dhawan', 8, 'Indian', 'Batsman', 'Left-handed bat', 'Right-arm off break'),
('Liam Livingstone', 8, 'English', 'All-rounder', 'Right-handed bat', 'Leg break googly'),
('Kagiso Rabada', 8, 'South African', 'Bowler', 'Left-handed bat', 'Right-arm fast'),
('Arshdeep Singh', 8, 'Indian', 'Bowler', 'Left-handed bat', 'Left-arm medium-fast'),
('Sam Curran', 8, 'English', 'All-rounder', 'Left-handed bat', 'Left-arm medium-fast'),
('Shubman Gill', 9, 'Indian', 'Batsman', 'Right-handed bat', NULL),
('Rashid Khan', 9, 'Afghan', 'Bowler', 'Right-handed bat', 'Leg break googly'),
('Mohammed Shami', 9, 'Indian', 'Bowler', 'Right-handed bat', 'Right-arm fast-medium'),
('Hardik Pandya', 9, 'Indian', 'All-rounder', 'Right-handed bat', 'Right-arm medium-fast'),
('David Miller', 9, 'South African', 'Batsman', 'Left-handed bat', NULL),
('KL Rahul', 10, 'Indian', 'Wicket-keeper Batsman', 'Right-handed bat', NULL),
('Marcus Stoinis', 10, 'Australian', 'All-rounder', 'Right-handed bat', 'Right-arm medium'),
('Ravi Bishnoi', 10, 'Indian', 'Bowler', 'Right-handed bat', 'Leg break'),
('Nicholas Pooran', 10, 'West Indian', 'Wicket-keeper Batsman', 'Left-handed bat', NULL),
('Krunal Pandya', 10, 'Indian', 'All-rounder', 'Left-handed bat', 'Left-arm orthodox');

select * from ipl_players 

CREATE TABLE ipl_scores (
    score_id SERIAL PRIMARY KEY,
    match_id INTEGER NOT NULL,
    team_id INTEGER NOT NULL,
    innings INTEGER NOT NULL,
    total_runs INTEGER NOT NULL,
    wickets_fallen INTEGER NOT NULL,
    overs_played DECIMAL(3,1) NOT NULL,
    FOREIGN KEY (match_id) REFERENCES ipl_matches(match_id),
    FOREIGN KEY (team_id) REFERENCES ipl_teams(team_id),
    UNIQUE (match_id, team_id, innings)
);


INSERT INTO ipl_scores (match_id, team_id, innings, total_runs, wickets_fallen, overs_played) VALUES
(1, 1, 1, 157, 7, 20.0),
(1, 2, 1, 150, 10, 19.4),
(2, 8, 1, 191, 5, 20.0),
(2, 4, 1, 186, 8, 20.0),
(3, 10, 1, 193, 6, 20.0),
(3, 5, 1, 143, 9, 17.0),
(4, 7, 1, 131, 8, 20.0),
(4, 6, 1, 132, 6, 19.2),
(5, 3, 1, 171, 2, 16.2),
(5, 1, 1, 170, 7, 20.0),
(6, 5, 1, 162, 8, 20.0),
(6, 9, 1, 163, 4, 19.3),
(7, 6, 1, 197, 4, 20.0),
(7, 8, 1, 198, 6, 19.5),
(8, 2, 1, 181, 7, 20.0),
(8, 10, 1, 169, 9, 19.3),
(9, 9, 1, 204, 4, 20.0),
(9, 4, 1, 197, 9, 20.0),
(10, 8, 1, 159, 9, 20.0),
(10, 10, 1, 157, 8, 19.4),
(11, 1, 1, 199, 6, 20.0),
(11, 3, 1, 182, 8, 20.0),
(12, 9, 1, 177, 7, 20.0),
(12, 6, 1, 179, 4, 19.4),
(13, 5, 1, 129, 8, 20.0),
(13, 1, 1, 130, 4, 18.1),
(14, 2, 1, 200, 5, 20.0),
(14, 6, 1, 192, 7, 20.0),
(15, 8, 1, 179, 7, 20.0),
(15, 9, 1, 180, 3, 19.2),
(16, 4, 1, 171, 6, 20.0),
(16, 7, 1, 166, 8, 20.0),
(17, 3, 1, 174, 5, 20.0),
(17, 5, 1, 151, 9, 18.4),
(18, 1, 1, 185, 6, 20.0),
(18, 4, 1, 169, 8, 19.3),
(19, 10, 1, 158, 6, 20.0),
(19, 9, 1, 125, 10, 18.1),
(20, 6, 1, 167, 7, 20.0),
(20, 10, 1, 157, 8, 19.1),
(21, 2, 1, 131, 5, 20.0),
(21, 4, 1, 132, 4, 18.3),
(22, 5, 1, 177, 4, 20.0),
(22, 1, 1, 176, 6, 19.4),
(23, 8, 1, 205, 5, 20.0),
(23, 3, 1, 203, 7, 20.0),
(24, 9, 1, 158, 5, 20.0),
(24, 10, 1, 156, 6, 19.4),
(25, 7, 1, 142, 10, 19.5),
(25, 6, 1, 203, 4, 20.0),
(26, 3, 1, 128, 7, 20.0),
(26, 4, 1, 132, 5, 19.0);







